//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geographymaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Badges = new HashSet<Badge>();
            this.InfoBoxes = new HashSet<InfoBox>();
            this.Questions = new HashSet<Question>();
            this.Subcategories = new HashSet<Subcategory>();
        }
    
        public long IdCategory { get; set; }
        public string Continent { get; set; }
    
        public virtual ICollection<Badge> Badges { get; set; }
        public virtual ICollection<InfoBox> InfoBoxes { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
}
