//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geographymaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint
    {
        public long IdHint { get; set; }
        public long IdQuestion { get; set; }
        public string Hint1 { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
