//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geographymaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Hints = new HashSet<Hint>();
        }
    
        public long IdQuestion { get; set; }
        public long IdCategory { get; set; }
        public string Question1 { get; set; }
        public int NoStars { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Hint> Hints { get; set; }
    }
}
