//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geographymaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public long IdSubcategory { get; set; }
        public string Subcategory1 { get; set; }
        public long IdCategory { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
